#!/bin/bash

POLYMAKEVERSION=3.3
POLYMAKELONGVERSION="Release 3.3 of February 2019"
POLYMAKEHOME=https://github.com/polymake/polymake
POLYMAKE_GIT_SERVER_RELEASE="https://github.com/polymake/polymake.git"
POLYMAKE_GIT_BRANCH_RELEASE='Releases'
POLYMAKE_GIT_SERVER_DEVEL="git@git.polymake.org:polymake"
POLYMAKE_GIT_BRANCH_DEVEL='master'

POLYMAKE_GIT_BRANCH=${POLYMAKE_GIT_BRANCH_RELEASE}
POLYMAKE_GIT_SERVER=${POLYMAKE_GIT_SERVER_RELEASE}

ANTVERSION=1.10.5
ANTHOME=http://ant.apache.org/
ANTNAME=apache-ant-$ANTVERSION-bin.tar.bz2
ANTBASE=http://artfiles.org/apache.org//ant/binaries

AUTOCONFVERSION=2.69
AUTOCONFHOME=https://www.gnu.org/software/autoconf/
AUTOCONFNAME=autoconf-$AUTOCONFVERSION.tar.gz
AUTOCONFBASE=http://ftp.gnu.org/gnu/autoconf

AUTOMAKEVERSION=1.16
AUTOMAKEHOME=https://www.gnu.org/software/automake/
AUTOMAKENAME=automake-$AUTOMAKEVERSION.tar.gz
AUTOMAKEBASE=http://ftp.gnu.org/gnu/automake

BOOSTVERSION=1_66_0
BOOSTVERSIONDIR=1.66.0
BOOSTHOME=http://www.boost.org/
BOOSTNAME=boost_$BOOSTVERSION.tar.bz2
BOOSTBASE=https://dl.bintray.com/boostorg/release/$BOOSTVERSIONDIR/source

CANARYVERSION=2012
CANARYHOME=https://metacpan.org/pod/Canary::Stability
CANARYNAME=Canary-Stability-$CANARYVERSION.tar.gz
CANARYBASE=https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN

CDDLIBVERSION=094h
CDDHOME=http://www.inf.ethz.ch/personal/fukudak/cdd_home/
CDDLIBNAME=cddlib-$CDDLIBVERSION.tar.gz
CDDLIBBASE=ftp://ftp.math.ethz.ch/users/fukudak/cdd

FTI2VERSION=1.6.9
FTI2VERSION_DIR=1_6_9
FTI2HOME=http://www.4ti2.de/
FTI2NAME=4ti2-$FTI2VERSION.tar.gz
FTI2BASE=https://github.com/4ti2/4ti2/releases/download/Release_$FTI2VERSION_DIR

GLPKVERSION=4.61
GLPKHOME=https://www.gnu.org/software/glpk/
GLPKNAME=glpk-$GLPKVERSION.tar.gz
GLPKBASE=http://ftp.gnu.org/gnu/glpk

GMPVERSION=6.1.2
GMPMINORVERSION=
GMPHOME=http://gmplib.org/
GMPNAME=gmp-$GMPVERSION$GMPMINORVERSION.tar.bz2
GMPBASE=https://gmplib.org/download/gmp

JREALITYVERSION=
JREALITYHOME=http://www3.math.tu-berlin.de/jreality

JSONVERSION=2.95
JSONHOME=https://metacpan.org/pod/JSON
JSONNAME=JSON-$JSONVERSION.tar.gz
JSONBASE=https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI

JSONXSVERSION=4.0
JSONXSHOME=https://metacpan.org/pod/Eve::Json
JSONXSNAME=JSON-XS-$JSONXSVERSION.tar.gz
JSONXSBASE=https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN

LIBTOOLVERSION=2.4
LIBTOOLHOME=
LIBTOOLNAME=libtool-$LIBTOOLVERSION.tar.gz
LIBTOOLBASE=http://ftp.gnu.org/gnu/libtool

LIBXSLTVERSION=1.96
LIBXSLTHOME=http://search.cpan.org/~shlomif/XML-LibXSLT/
LIBXSLTNAME=XML-LibXSLT-$LIBXSLTVERSION.tar.gz
LIBXSLTBASE=http://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF

LRSVERSION=4.2
LRSHOME=http://cgm.cs.mcgill.ca/~avis/C/lrs.html

MPFRVERSION=4.0.1
MPFRHOME=http://mpfr.org/
MPFRNAME=mpfr-$MPFRVERSION.tar.bz2
MPFRBASE=http://www.mpfr.org/mpfr-$MPFRVERSION

NAUTYVERSION=
NAUTYHOME=http://cs.anu.edu.au/~bdm/nauty/

NINJAVERSION="v1.8.2"
NINJANAME=ninja-mac.zip
NINJAHOME=https://ninja-build.org/
NINJABASE=https://github.com/ninja-build/ninja/releases/download/$NINJAVERSION

NORMALIZVERSION=3.5.0
NORMALIZHOME=https://www.normaliz.uni-osnabrueck.de

NTLVERSION=11.3.2
NTLNAME=ntl-$NTLVERSION.tar.gz
NTLHOME=http://www.shoup.net/ntl/
NTLBASE=http://www.shoup.net/ntl

PERMLIBVERSION=
PERMLIBHOME=http://www.math.uni-rostock.de/~rehn/software/permlib.html

PPLVERSION=1.2
PPLHOME=http://bugseng.com/products/ppl/

READLINEVERSION=6.3
READLINEHOME=http://tiswww.case.edu/php/chet/readline/rltop.html
READLINENAME=readline-$READLINEVERSION.tar.gz
READLINEBASE=ftp://ftp.cwru.edu/pub/bash/

SINGULARVERSION=4.0.3
SINGULARHOME=https://github.com/Singular/

SVGVERSION=2.84
SVGHOME=http://search.cpan.org/~manwar/SVG/
SVGNAME=SVG-$SVGVERSION.tar.gz
SVGBASE=http://search.cpan.org/CPAN/authors/id/M/MA/MANWAR

TERMRLGNUVERSION=1.35
TERMRLGNUHOME=http://search.cpan.org/dist/Term-ReadLine-Gnu/
TERMRLGNUNAME=Term-ReadLine-Gnu-$TERMRLGNUVERSION.tar.gz
TERMRLGNUBASE=http://search.cpan.org/CPAN/authors/id/H/HA/HAYASHI


JNIHEADERS=/System/Library/Frameworks/JavaVM.framework/Headers/
