#!/bin/bash

CURDIR=$(pwd)
TAR_DIR=${CURDIR}/src
TMP=${CURDIR}/tmp/

SED=/usr/bin/sed
PERL=/usr/bin/perl
CURL="/usr/bin/curl -O -L"
DATE=$(date +'%Y-%m-%d')

MACVERSION=$(sw_vers | grep -o "10[.][0-9]\+")
PERLVERSION=$(${PERL} --version | grep -o "5[.][0-9]*[.][0-9]")
PREFIX=${CURDIR}/polymake.app/Contents/Resources

CC="ccache clang"
CXX="ccache clang++"

CFLAGS="-m64 -march=x86-64 -fpic -DPIC"
CXXFLAGS="-m64 -march=x86-64  -fpic -DPIC"

