#!/bin/bash -x

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPTBASE=${SCRIPTDIR}/..

. $SCRIPTDIR/000_versions
. $SCRIPTDIR/010_variables

echo "extracting ant"
tar xfj ${TAR_DIR}/${ANTNAME} -C ${PREFIX}