#!/bin/bash -x

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPTBASE=${SCRIPTDIR}/..

. $SCRIPTDIR/000_versions
. $SCRIPTDIR/010_variables

echo "installing ninja"
cd ${PREFIX}/bin
if [[ ! -f ninja ]]; then 
    unzip ${TAR_DIR}/ninja-mac.zip;
fi
cd ${CURDIR}