#!/bin/bash



export SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"

if [[ -z ${VAR_READ} ]]; then
  . ${SCRIPTDIR}/versions
  . ${SCRIPTDIR}/variables
fi

exec 3>&1 4>&2

${INSTALLSCRIPTDIR}/110_create_skeleton
${INSTALLSCRIPTDIR}/120_fetch_sources
${INSTALLSCRIPTDIR}/130_install_ant
${INSTALLSCRIPTDIR}/140_install_boost
${INSTALLSCRIPTDIR}/150_install_readline
${INSTALLSCRIPTDIR}/155_install_openssl
${INSTALLSCRIPTDIR}/160_install_perl_modules
${INSTALLSCRIPTDIR}/170_install_gmp
${INSTALLSCRIPTDIR}/180_install_mpfr
${INSTALLSCRIPTDIR}/190_install_glpk
${INSTALLSCRIPTDIR}/200_install_4ti2
${INSTALLSCRIPTDIR}/210_install_flint
${INSTALLSCRIPTDIR}/220_install_autotools
${INSTALLSCRIPTDIR}/230_install_ppl
${INSTALLSCRIPTDIR}/240_install_ntl
${INSTALLSCRIPTDIR}/250_install_singular
${INSTALLSCRIPTDIR}/260_install_ninja
${INSTALLSCRIPTDIR}/270_install_polymake
${INSTALLSCRIPTDIR}/280_fix_installation
${INSTALLSCRIPTDIR}/290_create_documentation
${INSTALLSCRIPTDIR}/300_diskimage

