#!/bin/bash

export  POLYMAKEVERSION=4.6
export  POLYMAKELONGVERSION="Release 4.6 of January 2022"
export  POLYMAKEHOME=https://github.com/polymake/polymake
export  POLYMAKE_GIT_SERVER_RELEASE="https://github.com/polymake/polymake.git"
export  POLYMAKE_GIT_BRANCH_RELEASE='Releases'
export  POLYMAKE_GIT_SERVER_DEVEL="git@git.polymake.org:polymake"
export  POLYMAKE_GIT_BRANCH_DEVEL='master'

export  POLYMAKE_GIT_BRANCH=${POLYMAKE_GIT_BRANCH_RELEASE}
export  POLYMAKE_GIT_SERVER=${POLYMAKE_GIT_SERVER_RELEASE}

export  ANTVERSION=1.10.12
export  ANTHOME=http://ant.apache.org/
export  ANTNAME=apache-ant-$ANTVERSION-bin.tar.bz2
export  ANTBASE=http://artfiles.org/apache.org//ant/binaries

# the newer 2.70 does not work
export  AUTOCONFVERSION=2.69
export  AUTOCONFHOME=https://www.gnu.org/software/autoconf/
export  AUTOCONFNAME=autoconf-$AUTOCONFVERSION.tar.gz
export  AUTOCONFBASE=http://ftp.gnu.org/gnu/autoconf

export  AUTOMAKEVERSION=1.16
export  AUTOMAKEHOME=https://www.gnu.org/software/automake/
export  AUTOMAKENAME=automake-$AUTOMAKEVERSION.tar.gz
export  AUTOMAKEBASE=http://ftp.gnu.org/gnu/automake

export  BOOSTVERSION=1_78_0
export  BOOSTVERSIONDIR=1.78.0
export  BOOSTHOME=http://www.boost.org/
export  BOOSTNAME=boost_$BOOSTVERSION.tar.bz2
export  BOOSTBASE=https://boostorg.jfrog.io/artifactory/main/release/$BOOSTVERSIONDIR/source/

export  CANARYVERSION=2013
export  CANARYHOME=https://metacpan.org/pod/Canary::Stability
export  CANARYNAME=Canary-Stability-$CANARYVERSION.tar.gz
export  CANARYBASE=https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN

export  CDDLIBVERSION=0.94m
export  CDDHOME=http://www.inf.ethz.ch/personal/fukudak/cdd_home/
export  CDDLIBNAME=cddlib-$CDDLIBVERSION.tar.gz
export  CDDLIBBASE=https://github.com/cddlib/cddlib/releases/download/0.94m

export  FTI2VERSION=1.6.9
export  FTI2VERSION_DIR=1_6_9
export  FTI2HOME=http://www.4ti2.de/
export  FTI2NAME=4ti2-$FTI2VERSION.tar.gz
export  FTI2BASE=https://github.com/4ti2/4ti2/releases/download/Release_$FTI2VERSION_DIR

export  GLPKVERSION=5.0
export  GLPKHOME=https://www.gnu.org/software/glpk/
export  GLPKNAME=glpk-$GLPKVERSION.tar.gz
export  GLPKBASE=http://ftp.gnu.org/gnu/glpk

export  OPENSSLVERSION=1.1.1m
export  OPENSSLHOME=https://www.openssl.org
export  OPENSSLNAME=openssl-$OPENSSLVERSION.tar.gz
export  OPENSSLBASE=https://www.openssl.org/source/

export  GMPVERSION=6.2.1
export  GMPMINORVERSION=
export  GMPHOME=http://gmplib.org/
export  GMPNAME=gmp-$GMPVERSION$GMPMINORVERSION.tar.bz2
export  GMPBASE=https://gmplib.org/download/gmp

export  JREALITYVERSION=
export  JREALITYHOME=http://www3.math.tu-berlin.de/jreality

export  JSONVERSION=4.05
export  JSONHOME=https://metacpan.org/pod/JSON
export  JSONNAME=JSON-$JSONVERSION.tar.gz
export  JSONBASE=https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI

export  EXTUTILSVERSION=7.64
export  EXTUTILSHOME=https://metacpan.org/pod/ExtUtils::MakeMaker
export  EXTUTILSNAME=ExtUtils-MakeMaker-$EXTUTILSVERSION.tar.gz
export  EXTUTILSBASE=https://cpan.metacpan.org/authors/id/B/BI/BINGOS/

export  JSONPPVERSION=4.07
export  JSONPPHOME=https://metacpan.org/pod/JSON::PP
export  JSONPPNAME=JSON-PP-$JSONPPVERSION.tar.gz
export  JSONPPBASE=https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI

export  XMLSAXVERSION=1.02
export  XMLSAXHOME=https://metacpan.org/pod/XML::SAX
export  XMLSAXNAME=XML-SAX-$XMLSAXVERSION.tar.gz
export  XMLSAXBASE=https://cpan.metacpan.org/authors/id/G/GR/GRANTM/

export  JSONMAYBEXSVERSION=1.004003
export  JSONMAYBEXSHOME=https://metacpan.org/pod/JSON::MaybeXS
export  JSONMAYBEXSNAME=JSON-MaybeXS-$JSONMAYBEXSVERSION.tar.gz
export  JSONMAYBEXSBASE=https://cpan.metacpan.org/authors/id/E/ET/ETHER

export  TYPESSERIALISERVERSION=1.01
export  TYPESSERIALISERHOME=https://metacpan.org/pod/Types::Serialiser
export  TYPESSERIALISERNAME=Types-Serialiser-$TYPESSERIALISERVERSION.tar.gz
export  TYPESSERIALISERBASE=https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/

export  COMMONSENSEVERSION=3.75
export  COMMONSENSEVHOME=https://metacpan.org/pod/distribution/common-sense/sense.pod
export  COMMONSENSENAME=common-sense-$COMMONSENSEVERSION.tar.gz
export  COMMONSENSEBASE=https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/

export  JSONXSVERSION=4.03
export  JSONXSHOME=https://metacpan.org/pod/JSON::XS
export  JSONXSNAME=JSON-XS-$JSONXSVERSION.tar.gz
export  JSONXSBASE=https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN

export MODULERUNTIMEVERSION=0.013
export MODULERUNTIMEHOME=https://metacpan.org/pod/Module::Runtime
export MODULERUNTIMENAME=Module-Runtime-$MODULERUNTIMEVERSION.tar.gz
export MODULERUNTIMEBASE=https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/

export NETSSLEAYVERSION=1.92
export NETSSLEAYHOME=https://metacpan.org/pod/Net::SSLeay
export NETSSLEAYNAME=Net-SSLeay-$NETSSLEAYVERSION.tar.gz
export NETSSLEAYBASE=https://cpan.metacpan.org/authors/id/C/CH/CHRISN/

export MONGODBVERSION=v2.2.2
export MONGODBHOME=https://metacpan.org/pod/MongoDB#VERSION
export MONGODBNAME=MongoDB-$MONGODBVERSION.tar.gz
export MONGODBBASE=https://cpan.metacpan.org/authors/id/M/MO/MONGODB/

export MOZILLACAVERSION=20211001
export MOZILLACAHOME=https://metacpan.org/pod/Mozilla::CA
export MOZILLACANAME=Mozilla-CA-$MOZILLACAVERSION.tar.gz
export MOZILLACABASE=https://cpan.metacpan.org/authors/id/A/AB/ABH/

export  LIBTOOLVERSION=2.4.6
export  LIBTOOLHOME=
export  LIBTOOLNAME=libtool-$LIBTOOLVERSION.tar.gz
export  LIBTOOLBASE=http://ftp.gnu.org/gnu/libtool

export  LIBXSLTVERSION=1.99
export  LIBXSLTHOME=http://search.cpan.org/~shlomif/XML-LibXSLT/
export  LIBXSLTNAME=XML-LibXSLT-$LIBXSLTVERSION.tar.gz
export  LIBXSLTBASE=http://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF

export  LRSVERSION=7.1
export  LRSHOME=http://cgm.cs.mcgill.ca/~avis/C/lrs.html

export  MPFRVERSION=4.1.0
export  MPFRHOME=http://mpfr.org/
export  MPFRNAME=mpfr-$MPFRVERSION.tar.bz2
export  MPFRBASE=http://www.mpfr.org/mpfr-$MPFRVERSION

export  NAUTYVERSION=
export  NAUTYHOME=http://cs.anu.edu.au/~bdm/nauty/

export  NINJAVERSION="v1.10.2"
export  NINJANAME=ninja-mac.zip
export  NINJAHOME=https://ninja-build.org/
export  NINJABASE=https://github.com/ninja-build/ninja/releases/download/$NINJAVERSION

export  NORMALIZVERSION=3.8.9
export  NORMALIZHOME=https://www.normaliz.uni-osnabrueck.de

export  NTLVERSION=11.5.1
export  NTLNAME=ntl-$NTLVERSION.tar.gz
export  NTLHOME=http://www.shoup.net/ntl/
export  NTLBASE=http://www.shoup.net/ntl

export  PERMLIBVERSION=
export  PERMLIBHOME=http://www.math.uni-rostock.de/~rehn/software/permlib.html

export  PPLVERSION=1.2
export  PPLHOME=http://bugseng.com/products/ppl/

export  READLINEVERSION=8.1
export  READLINEHOME=http://tiswww.case.edu/php/chet/readline/rltop.html
export  READLINENAME=readline-$READLINEVERSION.tar.gz
export  READLINEBASE=ftp://ftp.cwru.edu/pub/bash/

export  SINGULARVERSION=4.2.0
export  SINGULARTAG=Release-4-2-0
export  SINGULARHOME=https://github.com/Singular/

export  SVGVERSION=2.86
export  SVGHOME=http://search.cpan.org/~manwar/SVG/
export  SVGNAME=SVG-$SVGVERSION.tar.gz
export  SVGBASE=http://search.cpan.org/CPAN/authors/id/M/MA/MANWAR

export  TERMRLGNUVERSION=1.42
export  TERMRLGNUHOME=http://search.cpan.org/dist/Term-ReadLine-Gnu/
export  TERMRLGNUNAME=Term-ReadLine-Gnu-$TERMRLGNUVERSION.tar.gz
export  TERMRLGNUBASE=http://search.cpan.org/CPAN/authors/id/H/HA/HAYASHI


export  JNIHEADERS=/System/Library/Frameworks/JavaVM.framework/Headers/
