#!/bin/sh

if [[ -f $HOME/.polymake-macbundle/bundle.config ]]; then
. $HOME/.polymake-macbundle/bundle.config
fi

term="Terminal"
if [[ -n "${POLYMAKE_TERM}" ]]; then
  term=${POLYMAKE_TERM}
fi

dirtmp=$(cd "$(dirname "$0")"; pwd)
dir=`echo $dirtmp | awk '{ print $1 }'`
open -a $term $dir/polymake.start
exit 0
