#!/bin/bash -x

if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/functions

function fetch_src {
    cd $TAR_DIR
    if [ ! -f  $1 ]; then 
        echo "fetching $1"
        $CURL $2/$1
    fi
    cd $CURDIR
} 

mkdir -p ${TAR_DIR}

set_prefix "fetch sources"
fetch_src $ANTNAME $ANTBASE
fetch_src $FTI2NAME $FTI2BASE
fetch_src $OPENSSLNAME $OPENSSLBASE
fetch_src $TERMRLGNUNAME $TERMRLGNUBASE
fetch_src $LIBXSLTNAME $LIBXSLTBASE
fetch_src $TYPESSERIALISERNAME $TYPESSERIALISERBASE
fetch_src $COMMONSENSENAME $COMMONSENSEBASE
fetch_src $JSONXSNAME $JSONXSBASE
fetch_src $JSONMAYBEXSNAME $JSONMAYBEXSBASE
fetch_src $CANARYNAME $CANARYBASE
fetch_src $JSONNAME $JSONBASE
fetch_src $SVGNAME $SVGBASE
fetch_src $MODULERUNTIMENAME $MODULERUNTIMEBASE
fetch_src $NETSSLEAYNAME $NETSSLEAYBASE
fetch_src $MONGODBNAME $MONGODBBASE
fetch_src $MOZILLACANAME $MOZILLACABASE
fetch_src $BOOSTNAME $BOOSTBASE
fetch_src $GMPNAME $GMPBASE
fetch_src $MPFRNAME $MPFRBASE
fetch_src $READLINENAME $READLINEBASE
fetch_src $AUTOCONFNAME $AUTOCONFBASE
fetch_src $AUTOMAKENAME $AUTOMAKEBASE
fetch_src $LIBTOOLNAME $LIBTOOLBASE
fetch_src $NTLNAME $NTLBASE
fetch_src $CDDLIBNAME $CDDLIBBASE
fetch_src $GLPKNAME $GLPKBASE
fetch_src $NINJANAME $NINJABASE