#!/bin/bash -x

if [[ -s ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi

echo "extracting ant"
tar xfj ${TAR_DIR}/${ANTNAME} -C ${PREFIX}