#!/bin/bash -x

if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/functions

echo "extracting ant"
set_prefix "extracting ant"
tar xfj ${TAR_DIR}/${ANTNAME} -C ${PREFIX}