#!/bin/bash -x

if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/functions

echo "extracting boost"
set_prefix "extracting boost"
tar xfj ${TAR_DIR}/${BOOSTNAME} -C ${PREFIX}/include

echo "removing unneeded parets of boost"
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSIONDIR}/doc
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSIONDIR}/tools
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSIONDIR}/status
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSIONDIR}/more
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSIONDIR}/libs