#!/bin/bash -x

DIR="$(cd "$(dirname "$0")" && pwd)"
export SCRIPTDIR=${DIR}/..
if [[ -z ${VAR_READ} ]]; then
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/installer/functions

echo "extracting boost"
#set_prefix "extracting boost"
tar xfj ${TAR_DIR}/${BOOSTNAME} -C ${PREFIX}/include

echo "removing unneeded parts of boost"
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSION}/doc
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSION}/tools
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSION}/status
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSION}/more
rm -rf polymake.app/Contents/Resources/include/boost_${BOOSTVERSION}/libs