#!/bin/bash -x

if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi

echo "building readline"
mkdir -p ${TMP}
tar xfz ${TAR_DIR}/${READLINENAME} -C ${TMP}

cd ${TMP}/readline-${READLINEVERSION}

if [ "${MACVERSION}" = "10.8" ]; then
	${SED} -i '' -e 's|-arch_only `/usr/bin/arch`|-dynamiclib|g' support/shobj-conf;
else
    ${SED} -i '' -e "s|SHOBJ_ARCHFLAGS=|SHOBJ_ARCHFLAGS=\'-dynamiclib\'|g" support/shobj-conf;
fi

CFLAGS=${CFLAGS} CPPFLAGS=${CXXFLAGS}  ./configure --prefix=${PREFIX}
make
make install
cd ${CURDIR}