#!/bin/bash -x

if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/functions

set_prefix "building gmp"
echo "building gmp"
${FUNCDIR}/build.sh gmp-${GMPVERSION} ${TAR_DIR} gmp-${GMPVERSION} "${TMP}" build --prefix=${PREFIX} --enable-cxx=yes CFLAGS="${CFLAGS}" CPPFLAGS="${CXXFLAGS}"
cd ${CURDIR}

echo "installing gmp"
${FUNCDIR}/install.sh gmp-${GMPVERSION} "${TMP}" build
cd ${CURDIR}