#!/bin/bash -x

DIR="$(cd "$(dirname "$0")" && pwd)"
export SCRIPTDIR=${DIR}/..
if [[ -z ${VAR_READ} ]]; then
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/installer/functions

#set_prefix "building mpfr"
echo "building mpfr"
${FUNCDIR}/build.sh mpfr-${MPFRVERSION} ${TAR_DIR} mpfr-${MPFRVERSION} "${TMP}" build --prefix=${PREFIX} --with-gmp=${PREFIX} LDFLAGS="-Wl,-rpath,${PREFIX}/lib"  CFLAGS="${CFLAGS}" CPPFLAGS="${CXXFLAGS}"

echo "installing mpfr"
${FUNCDIR}/install.sh mpfr-${MPFRVERSION} "${TMP}" build
cd ${CURDIR}