#!/bin/bash -x

if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi

echo "building perl modules"
echo "building Term-Readline-Gnu"
tar xvfz ${TAR_DIR}/${TERMRLGNUNAME} -C ${TMP}
cd ${TMP}/Term-ReadLine-Gnu-${TERMRLGNUVERSION}
${SED} -i '' -e "s|Config{cc}|Config{cc} -Wl,-rpath,${PREFIX}/lib|g" Makefile.PL
ARCHFLAGS='-arch x86_64' ${PERL} Makefile.PL --includedir=${PREFIX}/include --libdir=${PREFIX}/lib
make
make install
cd ${CURDIR}

curl -L https://cpanmin.us | perl - App::cpanminus
#cpanm --local-lib $PERL_MP_OPT local::lib
cpanm XML::LibXSLT
cpanm SVG
cpanm Moo
cpanm ZEFRAM/Module-Runtime-0.013.tar.gz
cpanm MongoDB
cpanm JSON::XS
cpanm JSON

