#!/bin/bash -x

if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi


echo "building glpk"
${FUNCDIR}/build.sh glpk-${GLPKVERSION} ${TAR_DIR} glpk-${GLPKVERSION} "${TMP}" build \
								--prefix=${PREFIX} --with-gmp CFLAGS="-I${PREFIX}/include"  CXXFLAGS="-I${PREFIX}/include" LDFLAGS="-L${PREFIX}/lib -Wl,-rpath,${PREFIX}/lib"

${FUNCDIR}/install.sh glpk-${GLPKVERSION} "${TMP}" build