#!/bin/bash -x

DIR="$(cd "$(dirname "$0")" && pwd)"
export SCRIPTDIR=${DIR}/..
if [[ -z ${VAR_READ} ]]; then
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/installer/functions

#set_prefix "building autotools"
echo "building autoconf"
mkdir -p ${TMP}/local
tar xfz ${TAR_DIR}/autoconf-${AUTOCONFVERSION}.tar.gz -C ${TMP}
cd ${TMP}/autoconf-${AUTOCONFVERSION}
./configure --prefix=${TMP}/local
make && make install
cd ${CURDIR}

echo "building automake"
tar xfz ${TAR_DIR}/automake-${AUTOMAKEVERSION}.tar.gz -C ${TMP}
cd ${TMP}/automake-${AUTOMAKEVERSION}
PATH=${TMP}/local/bin:${PATH} ./configure --prefix=${TMP}/local
make && make install
cd ${CURDIR}

echo "building libtool"
tar xfz ${TAR_DIR}/libtool-${LIBTOOLVERSION}.tar.gz -C ${TMP}
cd ${TMP}/libtool-${LIBTOOLVERSION}
PATH=${TMP}/local/bin:${PATH} ./configure --prefix=${TMP}/local
make && make install
cd ${CURDIR}

