#!/bin/bash -x


if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/functions

echo "installing ninja"
set_prefix "installing ninja"
cd ${PREFIX}/bin
if [[ ! -f ninja ]]; then 
    unzip ${TAR_DIR}/ninja-mac.zip;
fi
cd ${CURDIR}