#!/bin/bash -x

if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi

echo "installing ninja"
cd ${PREFIX}/bin
if [[ ! -f ninja ]]; then 
    unzip ${TAR_DIR}/ninja-mac.zip;
fi
cd ${CURDIR}