#!/bin/bash -x


DIR="$(cd "$(dirname "$0")" && pwd)"
export SCRIPTDIR=${DIR}/..
if [[ -z ${VAR_READ} ]]; then
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/installer/functions

echo "installing ninja"
#set_prefix "installing ninja"
cd ${PREFIX}/bin
if [[ ! -f ninja ]]; then 
    unzip ${TAR_DIR}/ninja-mac.zip;
fi
cd ${CURDIR}