#!/bin/bash -x



if [[ -z ${VAR_READ} ]]; then
    DIR="$(cd "$(dirname "$0")" && pwd)"
    export SCRIPTDIR=${DIR}/..
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/functions

set_prefix "fixing installation"

echo "fixing paths in libraries"
${FUNCDIR}/fix_load_dylib.sh ${PREFIX}/lib ${PREFIX} dylib
${FUNCDIR}/fix_load_dylib.sh ${PREFIX}/bin ${PREFIX} ""
${FUNCDIR}/fix_load_dylib.sh ${PREFIX}/polymake/lib ${PREFIX} dylib
${FUNCDIR}/fix_load_dylib.sh ${PREFIX}/polymake/lib/polymake/lib ${PREFIX} bundle
${FUNCDIR}/fix_load_dylib.sh ${PREFIX}/polymake/lib/polymake/lib ${PREFIX} dylib
${FUNCDIR}/fix_load_dylib.sh ${PREFIX}/perl5/lib/perl5/darwin-thread-multi-2level/auto/Term/ReadLine/Gnu ${PREFIX} bundle
${FUNCDIR}/fix_load_dylib.sh ${PREFIX}/polymake/lib/polymake/perlx/${PERLVERSION}/darwin-thread-multi-2level/auto/Polymake/Ext ${PREFIX} bundle
for ext in ${shell ls polymake.app/Contents/Resources/polymake/lib/polymake/bundled/ | sed 's|/||'}; do \
	${FUNCDIR}/fix_load_dylib.sh ${PREFIX}/polymake/lib/polymake/bundled/$$ext/lib ${PREFIX} bundle ; \
done
${FUNCDIR}/fix_rpath.sh ${PREFIX}/lib ${PREFIX}/lib dylib
${FUNCDIR}/fix_rpath.sh ${PREFIX}/bin ${PREFIX}/lib ""
${FUNCDIR}/fix_rpath.sh ${PREFIX}/polymake/lib ${PREFIX}/lib dylib
${FUNCDIR}/fix_rpath.sh ${PREFIX}/polymake/lib/polymake/lib ${PREFIX}/lib bundle
${FUNCDIR}/fix_rpath.sh ${PREFIX}/polymake/lib/polymake/lib ${PREFIX}/lib dylib
${FUNCDIR}/fix_rpath.sh ${PREFIX}/polymake/lib/polymake/perlx/${PERLVERSION}/darwin-thread-multi-2level/auto/Polymake/Ext ${PREFIX}/lib bundle
for ext in ${shell ls polymake.app/Contents/Resources/polymake/lib/polymake/bundled/ | sed 's|/||'}; do \
	${FUNCDIR}/fix_rpath.sh ${PREFIX}/polymake/lib/polymake/bundled/$$ext/lib ${PREFIX}/lib bundle ; \
done
${FUNCDIR}/fix_libname.sh "${PREFIX}/lib" dylib ""
${FUNCDIR}/fix_libname.sh "${PREFIX}/polymake/lib" dylib "../polymake/lib"
${FUNCDIR}/fix_libname.sh "${PREFIX}/polymake/lib/polymake/lib" dylib "../polymake/lib/polymake/lib"

cd ${CURDIR}

### remove junk
echo "clean install"
cd polymake.app
find . -name "*.pod" -exec rm -rf {} \;
find . -name "*.3pm" -exec rm -rf {} \;
find . -name "*.packlist" -exec rm -rf {} \;
find . -name "*.la" -exec rm -rf {} \;
find . -name "*.pc" -exec rm -rf {} \;
rm -f Contents/Resources/bin/libpolys-config
rm -f Contents/Resources/bin/libsingular-config
rmdir Contents/Resources/lib/pkgconfig/

cd ${CURDIR}
