#!/bin/bash -x



DIR="$(cd "$(dirname "$0")" && pwd)"
export SCRIPTDIR=${DIR}/..
if [[ -z ${VAR_READ} ]]; then
    . ${SCRIPTDIR}/versions
    . ${SCRIPTDIR}/variables
fi
. ${SCRIPTDIR}/installer/functions

#set_prefix "creating dmg"

if [ -d /Volumes/polybundle ]; then
  echo "bundle dmg is already mounted, exiting";
  exit;
fi;

# change into the base directory
BUNDLEDIR=$1
SED="/usr/bin/sed"

mkdir -p ${CURDIR}/dmg

cd ${CURDIR}/dmg
hdiutil convert ${SCRIPTDIR}/template.dmg -format UDSP -o polybundle

hdiutil mount polybundle.sparseimage

sudo cp -a ${CURDIR}/polymake.app /Volumes/polybundle/
chmod a-w /Volumes/polybundle/polymake.app/Contents/Resources/polymake/lib/polymake/lib/*.bundle
sudo cp -a ${TAR_DIR} /Volumes/polybundle/src
sudo cp -a ${SCRIPTBASE}/bundle_scripts /Volumes/polybundle/src
sudo cp -a ${SCRIPTDIR} /Volumes/polybundle/src
sudo cp -a ${CURDIR}/README.pdf /Volumes/polybundle/

hdiutil eject /Volumes/polybundle

cd ${CURDIR}/dmg
hdiutil convert polybundle.sparseimage -format UDBZ -o ${CURDIR}/dmg/polybundle.dmg

cd ..
mv ${CURDIR}/dmg/polybundle.dmg ${CURDIR}
rm -rf ${CURDIR}/dmg

echo "Now you can set the icon of the dmg. (Open the Info window of polybundle.dmg with Cmd-I and then drag the file bundle_scripts/pm-cube.icns onto the icon in the upper left corner of the Info window.)"
