#!/bin/bash


osascript << INPUT
tell application "Finder"
	activate
	set infoWindow1 to open information window of document file "pm-cube.icns" of folder "scripts" of folder "src" of disk "polybundle"
	tell application "System Events"
		keystroke tab
		keystroke "c" using command down
	end tell
	close infoWindow1
	
	set infoWindow2 to open information window of disk "polybundle"
	tell application "System Events"
		keystroke tab
		keystroke "v" using command down
	end tell
	close infoWindow2
end tell
INPUT
