#!/bin/bash

# change into the base directory
BASEPATH=$( (cd -P $(dirname $0) && pwd) )
BASEPATH=${BASEPATH%scripts}/dmg
SED="/usr/bin/sed"

mkdir dmg
cd ${BASEPATH}
cp -pr ../polymake.app .
rm -rf polymake.app/Contents/Resources/Bootstrap
psize=`du -ks $BASEPATH/polymake.app | awk '{ print $1 }'`
tsize=`du -ks $BASEPATH/../tarballs | awk '{ print $1 }'`
ssize=`du -ks $BASEPATH/../scripts | awk '{ print $1 }'`
rsize=`du -ks $BASEPATH/../scripts/README.pdf | awk '{ print $1 }'`
KB=$((psize+ssize)) 
KB=$((KB+rsize)) 
KB=$((KB+tsize)) 
# account for overhead
KB=$((KB*14/10)) 

echo "creating a disk image of size $KB..."
hdiutil create -size ${KB}k tmp.dmg -layout NONE 
MYDEV=`hdid -nomount tmp.dmg` 

echo "formatting, needs super user rights..."

sudo newfs_hfs -v polybundle $MYDEV 

cd $BASEPATH 
sync
hdiutil eject $MYDEV 
hdid tmp.dmg
cd $BASEPATH
sudo cp -a polymake.app /Volumes/polybundle/
chmod u-w /Volumes/polybundle/polymake.app/Contents/Resources/polymake/lib/polymake/lib/*.bundle 
mkdir /Volumes/polybundle/src
sudo cp -a ../tarballs /Volumes/polybundle/src
sudo cp -a ../scripts /Volumes/polybundle/src
cp ../Makefile /Volumes/polybundle/src/
cp ../install.sh /Volumes/polybundle/src/
cp ../fix_lc_load_dylib.sh /Volumes/polybundle/src/
cp ../fix_libname.sh /Volumes/polybundle/src/
cp ../build.sh /Volumes/polybundle/src/

cp ../scripts/README.pdf /Volumes/polybundle/

cd $BASEPATH
sync
sleep 30

@./custom_dmg

hdiutil eject $MYDEV
hdiutil convert -format UDZO tmp.dmg -o polybundle.dmg && rm tmp.dmg

cd ..
mv dmg/polybundle.dmg .
rm -rf dmg
